#!groovy
boolean isMaster = BRANCH_NAME == 'master'
String triggerCron = isMaster ? "30 5 * * *" : ""

properties([
  [
    $class  : 'BuildDiscarderProperty',
    pipelineTriggers([
        cron(triggerCron)
      ]),
    strategy: [$class: 'LogRotator', numToKeepStr: '5']
  ],
  pipelineTriggers([
    cron(triggerCron)
  ]),
  parameters([
    gitParameter(name: 'BRANCH_NAME', defaultValue: 'master', selectedValue: 'DEFAULT', type: 'PT_BRANCH'),
    string(name: 'RUNTIME_BRANCH', defaultValue: 'master', description: "The runtime branch to test against"),
  ])
])
node {
  try {
    env.JAVA_HOME = tool 'jdk-17.0.1';
    def mvnHome = tool "apache-maven-3.6.0";
    def nodeHome = tool 'node-18.16.0'
    env.PATH = "${env.JAVA_HOME}\\bin;${mvnHome}\\bin;${nodeHome};${env.PATH}";
    env.COMPOSE_PROJECT_NAME = "material-e2e-cypress";

    def cdsVersion;
    def dashboardVersion = '0.0.1-M16'
    def dcmListsVersion;

    stage('checkout') {
      checkout scm;
      bat "git checkout ${params.BRANCH_NAME}";
    }

    stage('install tools') {
      bat 'tools/_install-tools.bat'
      env.ANT_HOME = "${pwd()}\\tools\\apache-ant-1.10.3"
      env.PATH = "${env.ANT_HOME}\\bin;${env.PATH}"
    }

    stage('build') {
      withCredentials([file(credentialsId: 'npmrc_file', variable: 'npmrc_file')]) {
        bat "ant -f scripts/docker/build.xml build " +
          "-Ddocker.host=bq-build-lin.blueriq.local " +
          "-Dcommit=${env.GIT_COMMIT} " +
          "-DisRelease=false " +
          "-DnpmrcFileLocation=${npmrc_file}"
      }
    }

    try {
      stage('docker prepare') {
        withCredentials([file(credentialsId: 'BLUERIQ_LICENSE_15', variable: 'license_file')]) {
          writeFile file: './cypress/docker/config/license.aql', text: readFile(license_file)
        }
        bat "yarn e2e:docker-prepare -overrideVersion=true -runtimeBranch=${params.RUNTIME_BRANCH} -runtimeUrl=${env.RUNTIME_GIT_URL}";
      }
      stage('e2e tests') {
        withCredentials([file(credentialsId: 'npmrc_file', variable: 'npmrc_file')]) {
          bat "ant -f scripts/docker/e2e.xml run " +
            "-Ddocker.host=bq-docker-lin.blueriq.local " +
            "-Dcommit=${env.GIT_COMMIT} " +
            "-DnpmrcFileLocation=${npmrc_file}"
        }
      }
     }
     finally {
       stage('docker down') {
         bat "yarn e2e:docker-down";
       }
     }

     try {
      stage('docker prepare dashboards') {
       withCredentials([file(credentialsId: 'BLUERIQ_LICENSE_15', variable: 'license_file')]) {
          writeFile file: './cypress/docker/dashboards/config/runtime/license.aql', text: readFile(license_file)
          writeFile file: './cypress/docker/dashboards/config/case-engine/license.aql', text: readFile(license_file)
        }
        bat "yarn e2e:docker-prepare-dashboards -overrideVersion=true  -skipBuild=true -runtimeBranch=${params.RUNTIME_BRANCH} -runtimeUrl=${env.RUNTIME_GIT_URL}";
      }

      stage('e2e tests-dashboards') {
        withCredentials([file(credentialsId: 'npmrc_file', variable: 'npmrc_file')]) {
          bat "ant -f scripts/docker/e2e.xml run-e2e-dashboards " +
            "-Ddocker.host=bq-docker-lin.blueriq.local " +
            "-Dcommit=${env.GIT_COMMIT} " +
            "-DnpmrcFileLocation=${npmrc_file}"
        }
      }
    }
    finally {
      stage('docker down') {
        bat "yarn e2e:docker-down-dashboards";
      }
    }
  } catch (anyException) {
    echo "An error occured (${anyException}) marking build as failed.";
    currentBuild.result = 'FAILURE';
  } finally {
    stage("Publish results") {
      // Test results
      dir('cypress/report'){
            publishHTML([       allowMissing         : false,
                                alwaysLinkToLastBuild: false,
                                keepAll              : true,
                                reportDir            : 'mochareports',
                                reportFiles          : 'report.html',
                                reportName           : 'Cypress e2e report',
                                reportTitles         : 'Cypress e2e report'])
      }

      // archive integration outputs
      archiveArtifacts artifacts: 'cypress/videos/*, cypress/screenshots/**/*, cypress/snapshots/**/*.diff.png, tmp/e2e-logs.txt, cypress-visual-screenshots/diff/*, cypress-visual-screenshots/comparison/*'
    }
    notifyBuildStatus();
    deleteDir();
  }
}// node

def notifyBuildStatus() {
  // notify the person who started the build and the persons who's commits broke the build
  step([$class                  : 'Mailer',
        notifyEveryUnstableBuild: true,
        recipients              : emailextrecipients([
          [$class: 'CulpritsRecipientProvider'],
          [$class: 'RequesterRecipientProvider']
        ])
  ]);

  step([$class                  : 'Mailer',
        notifyEveryUnstableBuild: true,
        sendToIndividuals       : true
  ]);
}
