#!groovy

pipeline {
  agent any

  tools {
    jdk 'jdk-25'
    maven 'apache-maven-3.9'
    nodejs 'node-22.14.0'
    ant 'apache-ant-1.10'
  }

  environment {
    COMPOSE_PROJECT_NAME = 'material-e2e-cypress'
  }

  options {
    timeout(time: 60, unit: 'MINUTES')
    buildDiscarder logRotator(numToKeepStr: '5')
    disableConcurrentBuilds()
    lock('material-e2e-docker')
    ansiColor('xterm')
  }

  parameters {
    string(name: 'RUNTIME_BRANCH', defaultValue: 'master', description: "The runtime branch to test against")
  }

  stages {
    stage('build') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'npm-readonly', usernameVariable: 'NPM_USERNAME', passwordVariable: 'NPM_PASSWORD')]) {
          bat "ant -f scripts/docker/build.xml build " +
            "-Ddocker.host=bq-build-lin.blueriq.local " +
            "-Dcommit=${env.GIT_COMMIT} " +
            "-DisRelease=false"
        }
      }
    }

    stage('e2e') {
      stages {
        stage('docker prepare') {
          steps {
            withCredentials([file(credentialsId: 'BLUERIQ_RUNTIME_LICENSE', variable: 'license_file')]) {
              writeFile file: './cypress/docker/config/license.aql', text: readFile(license_file)
            }
            bat "pnpm run e2e:docker-prepare -overrideVersion true -inNetwork true -runtimeBranch ${params.RUNTIME_BRANCH} -runtimeUrl ${env.RUNTIME_GIT_URL}"
          }
        }

        stage('e2e tests') {
          steps {
            withCredentials([file(credentialsId: 'npmrc_file', variable: 'npmrc_file'),
                             usernamePassword(credentialsId: 'npm-readonly', usernameVariable: 'NPM_USERNAME', passwordVariable: 'NPM_PASSWORD')]) {
              bat "ant -f scripts/docker/e2e.xml run " +
                "-Ddocker.host=bq-docker-lin.blueriq.local " +
                "-Dcommit=${env.GIT_COMMIT} " +
                "-DnpmrcFileLocation=${npmrc_file}"
            }
          }
        }
      }
      post {
        always {
          bat 'pnpm run e2e:docker-down'
        }
      }
    }

    stage('e2e dashboards') {
      stages {
        stage('docker prepare dashboards') {
          steps {
            withCredentials([file(credentialsId: 'BLUERIQ_RUNTIME_LICENSE', variable: 'license_file')]) {
              writeFile file: './cypress/docker/dashboards/config/runtime/license.aql', text: readFile(license_file)
              writeFile file: './cypress/docker/dashboards/config/case-engine/license.aql', text: readFile(license_file)
            }
            bat "pnpm run e2e:docker-prepare-dashboards -overrideVersion true -skipBuild true -inNetwork true -runtimeBranch ${params.RUNTIME_BRANCH} -runtimeUrl ${env.RUNTIME_GIT_URL}"
          }
        }

        stage('e2e tests dashboards') {
          steps {
            withCredentials([file(credentialsId: 'npmrc_file', variable: 'npmrc_file'),
                             usernamePassword(credentialsId: 'npm-readonly', usernameVariable: 'NPM_USERNAME', passwordVariable: 'NPM_PASSWORD')]) {
              bat "ant -f scripts/docker/e2e.xml run-e2e-dashboards " +
                "-Ddocker.host=bq-docker-lin.blueriq.local " +
                "-Dcommit=${env.GIT_COMMIT} " +
                "-DnpmrcFileLocation=${npmrc_file}"
            }
          }
        }
      }
      post {
        always {
          bat 'pnpm run e2e:docker-down-dashboards'
        }
      }
    }
  }

  post {
    always {
      dir('cypress/report') {
        publishHTML([allowMissing         : true,
                     alwaysLinkToLastBuild: false,
                     keepAll              : true,
                     reportDir            : 'mochareports',
                     reportFiles          : 'report.html',
                     reportName           : 'Cypress e2e report',
                     reportTitles         : 'Cypress e2e report'])
      }

      // archive integration outputs
      archiveArtifacts artifacts: 'cypress/videos/*, cypress/screenshots/**/*, cypress/snapshots/**/*.diff.png, tmp/e2e-logs.txt, tmp/e2e-dashboards-logs.txt, cypress-visual-screenshots/diff/*, cypress-visual-screenshots/comparison/*',
        allowEmptyArchive: true

      notifyBuildStatus()
    }

    cleanup {
      deleteDir()
    }
  }
}

def notifyBuildStatus() {
  // notify the person who started the build and the persons who's commits broke the build
  step([$class                  : 'Mailer',
        notifyEveryUnstableBuild: true,
        sendToIndividuals       : false,
        recipients              : emailextrecipients([culprits(), requestor()]) + " ${DEVELOPERS_EMAIL}"
  ])
}
