version: '3'
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.RUNTIME
    depends_on:
      - postgres
  customerdata:
    build:
      context: .
      dockerfile: Dockerfile.CDS
    depends_on:
      - postgres
  mongodb:
    image: mongo:8.0.17
    restart: always
  blueriq-material-theme:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - runtime
  postgres:
    image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password!123
