version: '3'
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.RUNTIME
    ports:
      - "9082:8080"
  customerdata:
    build:
      context: .
      dockerfile: Dockerfile.CDS
    ports:
      - "9083:8080"
  mongodb:
    image: mongo:7.0.4@sha256:3ee80b67778b162efb3323c1f1539c573c9928c0540a567ebf5fec15d387327a
    restart: always
    ports:
      - "9084:27017"
  blueriq-material-theme:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9081:80"
    depends_on:
      - runtime
