version: '3'
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.RUNTIME
    ports:
      - "9082:8080"
    depends_on:
      - postgres
  customerdata:
    build:
      context: .
      dockerfile: Dockerfile.CDS
    ports:
      - "9083:8080"
    depends_on:
      - postgres
  mongodb:
    image: mongo:7.0.4@sha256:3ee80b67778b162efb3323c1f1539c573c9928c0540a567ebf5fec15d387327a
    restart: always
    ports:
      - "9084:27017"
  blueriq-material-theme:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9081:80"
    depends_on:
      - runtime
  postgres:
    image: postgres:16.2@sha256:4aea012537edfad80f98d870a36e6b90b4c09b27be7f4b4759d72db863baeebb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password!123
