version: '3'
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.RUNTIME
    ports:
      - "9082:8080"
    depends_on:
      - rabbitmq
  customerdata:
    build:
      context: .
      dockerfile: Dockerfile.CDS
    ports:
      - "9083:8080"
  mongodb:
    image: mongo:5.0.6-focal@sha256:2fea7c24de9fff67cf15cd36c369a5d3f8d8bc52a69b5b0b1778bd3d2f079e1b
    restart: always
    ports:
      - "9084:27017"
    deploy:
      resources:
        limits:
          memory: 256M
  blueriq-material-theme:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9081:80"
    depends_on:
      - runtime
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
