version: '3'
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.RUNTIME
    ports:
      - "9082:8080"
    depends_on:
      - rabbitmq
  customerdata:
    build:
      context: .
      dockerfile: Dockerfile.CDS
    ports:
      - "9083:8080"
  mongodb:
    image: mongo:4.2.3-bionic@sha256:2e24032659c947cb4748084f4516933bee66f4ef039e51cd9474710024022c9c
    restart: always
    ports:
      - "9084:27017"
    deploy:
      resources:
        limits:
          memory: 256M
  dcm-lists:
    build:
      context: .
      dockerfile: Dockerfile.DCMLISTS
    ports:
      - "9085:8080"
    depends_on:
      - mongodb
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.RABBIT
    restart: always
    ports:
      - "9086:15672"
  blueriq-material-theme:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9081:80"
    depends_on:
      - runtime
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
