FROM rabbitmq:3.7.22-management-alpine@sha256:0faee45add1d8d3f01709b9b2506019cd3a7999ee8662627a50b18e142a95d1c
ADD rabbitmq.conf /etc/rabbitmq/
ADD definitions.json /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf /etc/rabbitmq/definitions.json
CMD ["rabbitmq-server"]
