FROM rabbitmq:3.7.24-management-alpine@sha256:a75547bbfc90221df109870880fed1574ac1a0b08c7c53456b573050e1a67734
ADD rabbitmq.conf /etc/rabbitmq/
ADD definitions.json /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf /etc/rabbitmq/definitions.json
CMD ["rabbitmq-server"]
