FROM openjdk:17-jdk-buster@sha256:fcc1f2be2f2361da9a9f65754864218fe5fed86ea085ca39779114c91edfd41a

LABEL maintainer="support@blueriq.com"

COPY preparations/blueriq-gateway-service-*.jar ~/gateway-service.jar
COPY dashboards/config/gateway/blueriq-gateway-service.yaml /config/gateway-service/

WORKDIR ~

ENTRYPOINT ["java", "-Dspring.config.additional-location=file:///config/gateway-service/", "-jar", "gateway-service.jar", "-Xmx256m" ]
