FROM azul/zulu-openjdk-centos:21

LABEL maintainer="support@blueriq.com"

COPY preparations/blueriq-gateway-service-*.jar ~/gateway-service.jar
COPY dashboards/config/gateway/blueriq-gateway-service.yaml /config/gateway-service/

WORKDIR ~

ENTRYPOINT ["java", "-Dspring.config.additional-location=file:///config/gateway-service/", "-jar", "gateway-service.jar", "-Xmx256m" ]
