FROM azul/zulu-openjdk-centos:21

LABEL maintainer="support@blueriq.com"

ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
EXPOSE 8080 8000

COPY preparations/blueriq-dcm-lists-standalone-*.jar ~/dcm-lists.jar
COPY dashboards/config/dcm-lists/blueriq-dcm-lists.yml /config/blueriq-dcm-lists/

WORKDIR ~

ENTRYPOINT ["java", "-Dspring.config.additional-location=file:///config/blueriq-dcm-lists/", "-jar", "dcm-lists.jar", "-Xmx256m" ]
