FROM openjdk:17-slim@sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc126b41f68c3f62f9774
LABEL maintainer="support@blueriq.com"

ARG BLUERIQ_LICENSE

EXPOSE 8080 8000

COPY preparations/blueriq-runtime-standalone-*.jar ~/runtime.jar
COPY dashboards/config/case-engine /config/blueriq-case-engine/
COPY dashboards/config/exports /config/blueriq-case-engine/exports/

WORKDIR ~
ENTRYPOINT ["java", "-Dserver.servlet.context-path=/runtime", "-Dspring.config.additional-location=file:///config/blueriq-case-engine/", "-Djava.security.egd=file:/dev/./urandom", "-Dlogging.file.name=case-engine.log", "-Duser.timezone=Europe/Amsterdam", "-jar", "runtime.jar" ,"-Xmx512m", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"]