FROM nginx:1.28.0-alpine@sha256:8f2bcf97c473dfe311e79a510ee540ee02e28ce1e6a64e1ef89bfad32574ef10

ARG HOST_PORT=unset

COPY preparations/dist /usr/share/nginx/html
COPY dashboards/config/frontend/nginx.conf.template /nginx.conf.template
RUN envsubst '$$HOST_PORT' < /nginx.conf.template > /etc/nginx/conf.d/default.conf
