FROM openjdk:17-jdk-alpine@sha256:a996cdcc040704ec6badaf5fecf1e144c096e00231a29188596c784bcf858d05

LABEL maintainer="support@blueriq.com"

EXPOSE 8080

COPY preparations/blueriq-dcm-dashboard-service-standalone-*.jar ~/dashboard.jar
COPY dashboards/config/dashboard /config/blueriq-dashboard/

WORKDIR ~

ENTRYPOINT ["java", "-Dspring.config.additional-location=file:///config/blueriq-dashboard/", "-jar", "dashboard.jar", "-Xmx256m" ]
