FROM azul/zulu-openjdk-centos:21

LABEL maintainer="support@blueriq.com"

EXPOSE 8080

COPY preparations/blueriq-dcm-dashboard-service-standalone-*.jar ~/dashboard.jar
COPY dashboards/config/dashboard /config/blueriq-dashboard/

WORKDIR ~

ENTRYPOINT ["java", "-Dspring.config.additional-location=file:///config/blueriq-dashboard/", "-jar", "dashboard.jar", "-Xmx256m" ]
